name: CI

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y jv

    - name: Execute tests
      run: |
        # Commentted the original test file because the test requires the downloading of data so its expensive
        # ./tests.sh

        echo "Running tests (mocked)"

        # Mocking the test results
        mkdir -p ../data
        touch ../data/dataset1.sqlite
        touch ../data/dataset2.sqlite

        ./tests.sh
