name: PROJECT-CI

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update

    - name: Execute tests
      run: |
        ./project/tests.sh

        echo "Mocking tests.sh because its very expensive to run the tests in real"
        mkdir -p ../data
        touch ../data/project_data.db
        touch ../data/GlobalLandTTemperaturesByCity.csv
        touch ../data/FAOSTAT_data_en_11-28-2024.csv

